---
title: "Partition loss"
---
```{r}
here::i_am("notebooks/dPCR paper/partition_loss.Rmd")
library(ggplot2)
library(dplyr)
source(here::here("code", "utils_dists.R"))
source(here::here("code", "utils_dPCR_statistics.R"))
```
```{r}
partition_data <- readr::read_csv(here::here("data", "ww_data", "droplets_Stilla_Sapphire.csv"))
```

```{r}
partition_loss <- 30000 - partition_data$TotalDroplets

length(partition_loss)

set.seed(0)

mode_partition_loss <- 2400
mode_partition_loss_p <- mode_partition_loss/30000

bind_rows(
  data.frame(x = partition_loss, type = "Observed"),
  data.frame(x = rbeta(1000000, shape1 = 4.5, shape2 = 4.5*(1-mode_partition_loss_p)/mode_partition_loss_p + 2 - 1/mode_partition_loss_p) * 30000, type = "Simulated (beta)"),
  data.frame(x = plogis(rnorm(100000, mean = -2.2, sd = 0.5)) * 30000, type = "Simulated (logit-normal)")
) |> 
ggplot() + 
  geom_density(aes(x=x, color = type)) + 
  scale_color_manual(values = c("black", "blue", "red")) +
  xlab("Number of lost partitions") + ylab("Density") + 
  scale_x_continuous(expand = expansion(mult = c(0.,0.02))) +
  theme_bw() +
  theme(
    legend.position = "top",
    legend.title = element_blank()
    ) + 
  coord_cartesian(xlim = c(0, 30000))

ggsave(here::here("figures", "dPCR paper", "partition_loss.pdf"), width = 10, height = 5)
```
