---
title: "Inference of a single concentration"
---

Imports
```{r}
library(dplyr)
library(tidyr)
library(EpiSewer)
library(ggplot2)
library(ggdist)
```

```{r}
here::i_am("notebooks/dPCR paper/single_concentration.Rmd")
```


Setup
```{r}
concentrations <- c(1,3,5) # concentrations to infer
n_measured <- 100 # measurements per concentration
model_types <- list("Normal", "Log-Normal", "dPCR") # different models to compare
```

```{r}
rerun_models <- FALSE
```

Stan model for inference
```{r}
if (rerun_models) {
 EpiSewer_path <- find.package("EpiSewer")
 conc_model <- cmdstanr::cmdstan_model(
    here::here("code", "single_concentration.stan"),
    include_paths = file.path(EpiSewer_path, "stan")
  )
}
```

Fit all models
```{r}
if (rerun_models) {
  all_fits <- mapply(function(model_type, true_concentration) {
    
    # Simulate data
    set.seed(123) # seed ensures that all models get same data
    conc_data <- data.frame(
      date = rep(as.Date("1999-01-01"), n_measured),
      concentration = sim_conc_pre(
        lambda = true_concentration,
        n = 25000,
        c = 1.73e-5,
        cv = 0.1,
        n_replicates = 1,
        distribution = "lnorm",
        n_samples = n_measured
      ),
      replicate_id = 1:n_measured
    )
    
    # Specification of observation module
    if (model_type == "Normal") {
      md <- concentrations_observe(
        measurements = conc_data,
        replicate_col = "replicate_id",
        distribution = "normal"
      )
      md <- noise_estimate_constant_var(modeldata = md)
      md <- LOD_none(modeldata = md)
    } else if (model_type == "Log-Normal") {
      md <- concentrations_observe(
        measurements = conc_data,
        replicate_col = "replicate_id",
        distribution = "lognormal"
        )
      md <- noise_estimate(modeldata = md)
      md <- LOD_none(modeldata = md)
    } else if (model_type == "dPCR") {
      md <- concentrations_observe(
        measurements = conc_data,
        replicate_col = "replicate_id",
        distribution = "gamma"
      )
      md <- noise_estimate_dPCR(
        cv_prior_mu = 0.1, cv_prior_sigma = 0.01,
        total_partitions_prior_mu = 25000, total_partitions_prior_sigma = 0,
        partition_variation_prior_mu = 0, partition_variation_prior_sigma = 0,
        volume_scaled_prior_mu = 1.73e-5, volume_scaled_prior_sigma = 0,
        prePCR_noise_type = "lognormal", use_taylor_approx = FALSE,
        modeldata = md
        )
      md <- LOD_estimate_dPCR(modeldata = md)
    }
    
    # We provide a correctly specified prior with a CV of 50% around the true value
    md$concentration_prior <- c(true_concentration, true_concentration/2)
    md$.init$true_concentration <- true_concentration
    
    # prepare model data
    inits <- md$.init
    md <- suppressWarnings(rlang::flatten(md[!(names(md) %in% c(
      ".metainfo", ".checks", ".str", ".init",
      ".sewer_data", ".sewer_assumptions"
    ))]))
    md <- md[
      stringr::str_detect(names(md), c("_prior_text"), negate = TRUE)
    ]
    
    # fit model
    fit <- conc_model$sample(
      data = md,
      init = function() inits, seed = 0,
      chains = 4, parallel_chains = 4, adapt_delta = 0.99, max_treedepth = 15
    )
    fit$save_output_files(dir = tempdir(), basename = paste(model_type, true_concentration, sep = "_"))
    return(list(fit = fit, model_type = model_type, true_concentration = true_concentration))
  }, model_type = rep(model_types, length(concentrations)), true_concentration = rep(concentrations, each = length(model_types)), SIMPLIFY = FALSE)
  
  all_res <- lapply(all_fits, function(fit) {
    # extract results
    res_draws <- posterior::as_draws_df(fit$fit$draws(c("true_concentration", "predicted_concentration")))
    res_draws$model_type = fit$model_type
    res_draws$conc = fit$true_concentration
    return(res_draws)
  })
}
```

Gather results
```{r}
if (rerun_models) {
  result_data <- bind_rows(all_res) |> 
    mutate(
      model_type = factor(model_type, levels = c("Normal", "Log-Normal", "dPCR")),
      conc_text = paste(conc, "gc/mL")
      ) |> 
    pivot_longer(
      cols = c("true_concentration", "predicted_concentration"),
      names_to = "type", values_to = "value"
      ) |> 
    mutate(type = factor(type, levels = c("true_concentration", "predicted_concentration"), labels = c("Estimated", "Measured"))) |> 
    filter((type == "Measured" & value > -3 & value < 13) | (type == "Estimated" & value > 0 & value < 7))
  
  saveRDS(result_data, here::here("data", "results", "single_concentration_results.rds"))
}
```

```{r}
result_data <- readRDS(here::here("data", "results", "single_concentration_results.rds"))
```

Plot results
```{r}
result_data |> ggplot(aes(x = model_type, y = value)) +
  geom_hline(yintercept = 0, color = "grey") +
  geom_hline(
    data = data.frame(
      conc = concentrations, conc_text = paste(concentrations, "gc/mL")
      ), aes(yintercept = conc), color = "black", linetype = "dashed") +
  ggdist::stat_histinterval(aes(fill = model_type), alpha = 0.7, normalize = "panels") +
  scale_fill_manual(values = c("#d31f11","#f47a00","#007191")) +
  facet_grid(type~conc_text, scales = "free") +
  theme_bw() +
  theme(
    legend.position = "none",
    axis.title.x = element_blank(),
    strip.background = element_rect(fill = "#f2f2f2")
    ) +
  ylab("Concentration [gc/mL]")

ggsave(here::here("figures", "dPCR paper", "single_concentration.pdf"), width = 10, height = 6)
```

